# -*- coding: utf-8 -*-
"""Consegna1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1prBFBg5CcoCJqkd2a-jFupshpUtFsMpH
"""

#esercizio 1

def confronta(a,b):
  if a>(b**2)+4:
    return 1
  elif a<(b**2)+4:
    return -1
  else:
    return 0

#prove
print(confronta(9,2)) #1
print(confronta(7,2))#-1
print(confronta(8,2))#0
print(confronta(5,1))#0
print(confronta(3,1))#-1
print(confronta(10,2))#1

#esercizio 2

def divisori(lista_numeri):
  if len(lista_numeri)==0:
    return 0

  conta_divisori=0
  for i in range(len(lista_numeri)):
    if lista_numeri[i]!=0:
      for j in range(len(lista_numeri)):
        if i!=j and lista_numeri[j]%lista_numeri[i]==0:
          conta_divisori=conta_divisori+1
          break
  return conta_divisori

#prove
lista=[-3,-3,4,2,1]
print(divisori(lista))#4
lista=[0,0,-1,2,2,4]
print(divisori(lista))#4
lista=[1,-4,-2,-12,23]
print(divisori(lista))#3
lista=[]
print(divisori(lista))#0
lista=(-1,-2,-2)
print(divisori(lista))#3
lista=(4,2,1,0,4,2,0,8)
print(divisori(lista))#6
lista=(0,0,0,0,0)
print(divisori(lista))#0
lista=(0,1,2,3)
print(divisori(lista))#3
lista=(0,1,2,3,0)
print(divisori(lista))#3
lista=(0,2,0)
print(divisori(lista))#1
lista=(2,2,2)
print(divisori(lista))#3
lista=[1,0.5,2,3,1.5]
print(divisori(lista))#3
print(divisori([0.5,0.2,5,3,2]))

#esercizio 3

def conta_vocali(stringa):
  
  if len(stringa)==0:
    return 0

  contaVocali=0
  vocali=("a","e","i","o","u","A","E","I","O","U","à","è","ì","ò","ù","À","È","Ì","Ò","Ù","á","é","í","ó","ú","Á","É","Í","Ó","Ú")
  for c in stringa:
    if c in vocali:
      contaVocali=contaVocali+1
  return contaVocali

#prove
print(conta_vocali("pippo"))#2
print(conta_vocali("paperino"))#4
print(conta_vocali("plutO"))#2
print(conta_vocali(""))#0
print(conta_vocali("pippo pluto paperino"))#8
print(conta_vocali("abcd"))#1
print(conta_vocali("qwrtp"))#0
print(conta_vocali("aaAa"))#4
print(conta_vocali("PIPPO pippo PLUTO PaApà"))#8
print(conta_vocali("aeiouAEIOUàèìòùÀÈÌÒÙáéíóúÁÉÍÓÚ"))#30

#esercizio 4

def frequenza(stringa):
  diz={}
  for c in stringa:
    if diz.get(c,-1)!=-1:
      diz[c]=diz[c]+1
    else:
      diz[c]=1
      
  return diz

#prove
print(frequenza("aba bcc"))
print(frequenza("pippo e pluto"))
print(frequenza("PAoLa e pAolO @23"))
print(frequenza("     "))#5 spazi
print(frequenza(""))
print(frequenza("aeiouAEIOUàèìòùÀÈÌÒÙáéíóúÁÉÍÓÚ"))

